# -*- coding: utf-8 -*-
"""maxmin_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LDDLCQ3yCvmPUXNwQuZ7_ltQe9Gx0jh8
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile script_max.py
# n1 = int(input("Enter first number: "))
# n2 = int(input("Enter second number: "))
# if n1 > n2:
#   print(n1)
# else:
#   print(n2)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile script_min.py
# n1 = int(input("Enter first number: "))
# n2 = int(input("Enter second number: "))
# if n1 < n2:
#   print(n1)
# else:
#   print(n2)

